[build]
  command = "yarn build"  # Specify the build command
  publish = "dist"  # Specify the directory to publish

# You can add other configuration options as needed
# For example, environment variables, headers, redirects, etc.
